config/routes.rb
ReallyOneWebApp::Application.routes.draw do
  devise_for :users
  resources :house_lists
  root to: 'house_lists#index'

end

app/models/house_list.rb
class HouseList < ActiveRecord::Base
	attr_accessible :content, :user_id
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
   validates :first_name, presence: true
   validates :last_name, presence: true
   validates :profile_name, presence: true, 
   							uniqueness: true,
   							format: {
   								with: /a-zA-Z0-9_-/,
   								message: "Profile Names Cannot Contain Spaces"
   							}  
   

   has_many :house_lists
   def full_name
   		first_name +" "+ last_name
   	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_id, :first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :remember_me) }

  end
end

app/controllers/house_lists_controller.rb
class HouseListsController < ApplicationController
  before_action :set_house_list, only: [:show, :edit, :update, :destroy]

  # GET /house_lists
  # GET /house_lists.json
  def index
    @house_lists = HouseList.all
  end

  # GET /house_lists/1
  # GET /house_lists/1.json
  def show
  end

  # GET /house_lists/new
  def new
    @house_list = HouseList.new
  end

  # GET /house_lists/1/edit
  def edit
  end

  # POST /house_lists
  # POST /house_lists.json
  def create
    @house_list = HouseList.new(house_list_params)

    respond_to do |format|
      if @house_list.save
        format.html { redirect_to @house_list, notice: 'House list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @house_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @house_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /house_lists/1
  # PATCH/PUT /house_lists/1.json
  def update
    respond_to do |format|
      if @house_list.update(house_list_params)
        format.html { redirect_to @house_list, notice: 'House list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @house_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /house_lists/1
  # DELETE /house_lists/1.json
  def destroy
    @house_list.destroy
    respond_to do |format|
      format.html { redirect_to house_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house_list
      @house_list = HouseList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def house_list_params
      params.require(:house_list).permit(:city, :state, :zipCode, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/house_lists_helper.rb
module HouseListsHelper
end

app/views/house_lists/_form.html.erb
<%= simple_form_for(@house_list, html: {class: "form-horizontal"}) do |f| %>
  <% if @house_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house_list.errors.count, "error") %> prohibited this house_list from being saved:</h2>

      <ul>
      <% @house_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zipCode %>
  <%= f.input :address %><br />

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/house_lists/edit.html.erb
<h1>Editing house_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @house_list %> |
<%= link_to 'Back', house_lists_path %>

app/views/house_lists/index.html.erb
<div class = "page-header">
  <h1>House List</h1> 
</div>

  <%= link_to "Post a New House" , new_house_list_path , class: "btn btn-success" %>

  <% @house_lists.each do |house_list| %>
    <div class = "house_list">

      <sp><%= house_list.address %></sp>
      <sp><%= house_list.city %></sp>
      <sp><%= house_list.state %></sp>
      <sp><%= house_list.zipCode %></sp>
     
    <div class = "meta">
        <%= link_to time_ago_in_words(house_list.created_at) + " ago", house_list %>
        | <%= link_to "Show", house_list %> |
    </div> 
    <span class = "admin">
      <%= link_to "Edit" , edit_house_list_path(house_list) %> |
      <%= link_to 'Delete', house_list, method: :delete, data: { confirm: 'Are you sure you want to delete this house?' } %> |
    </span>

</div>
</div>
<% end %>

app/views/house_lists/new.html.erb
<h1>New house_list</h1>

<%= render 'form' %>

<%= link_to 'Back', house_lists_path %>

app/views/house_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @house_list.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @house_list.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @house_list.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @house_list.zipCode %>
</p>



<%= link_to 'Edit', edit_house_list_path(@house_list) %> |
<%= link_to 'Back', house_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReallyOneWebApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	
  <nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ReallyONE</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.first_name, edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %> 
          <li><%= link_to "Register", new_user_registration_path %></li> 
          <li><%= link_to "Sign In", new_user_session_path %></li> 
        <% end %>  
          
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav> 
   <div class = "container">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
									<%= yield %>
   </div>
</head>

<body>
</body>

</html>